# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c6557eb5080dcb02bbe482eb396da28cea9bd61df46138c185fdc3b6bebfe5fa8b8fee90b7c5b39b9d7d390268c63439dd9553a4164c05253f2fa25240aaf59

test:
  secret_key_base: 0478b4751a52988906bd092d59b66466b80ca7b7d99f40a4f07d40ce9c77acf28f5e740b2a5d7a3917adbe7dc235e5ed96b745ef6827a939b3f66bad9f06749f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
